// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMS_dotNet.Data;

#nullable disable

namespace SIMS_dotNet.Migrations
{
    [DbContext(typeof(SIMSContext))]
    [Migration("20250617161802_AddedItemTable")]
    partial class AddedItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIMS_dotNet.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("ItemAppearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemBatch")
                        .HasColumnType("int");

                    b.Property<double?>("ItemBoxHeight")
                        .HasColumnType("float");

                    b.Property<double?>("ItemBoxLenght")
                        .HasColumnType("float");

                    b.Property<double?>("ItemBoxWeight")
                        .HasColumnType("float");

                    b.Property<double?>("ItemBoxWidth")
                        .HasColumnType("float");

                    b.Property<string>("ItemColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ItemCost")
                        .HasColumnType("float");

                    b.Property<int?>("ItemDateOfFabrication")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ItemFormat")
                        .HasColumnType("float");

                    b.Property<string>("ItemMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemPerBox")
                        .HasColumnType("int");

                    b.Property<double?>("ItemStock")
                        .HasColumnType("float");

                    b.Property<string>("ItemSurfaceFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ItemSurfacePerBox")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SIMS_dotNet.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
